### ISSUE TITLE
[REQ] Postal

### ISSUE THREAD

**Issue by WybeBosch** [curseforge-mirror/.github#4]
Addon Name: Postal
Curseforge URL: https://www.curseforge.com/wow/addons/postal

It would seem that the current Postal link on this mirror github isnt working? 
(Using the url
[https://github.com/curseforge-mirror/postal](https://github.com/curseforge-mirror/postal)
)
When i try and import it into WoWup it says "A valid zip file is required to  be in the release order in order for WoWUp to download it"

Is this a incorrect implementation of it in the mirror? Or does the curseforge addon have something weird on their end perhaps?

ps. Your new-openables addon is awesome.

**Comment by srhinos** [comment]
oh ty for this, this is super annoying. I'll have to write more code to determine the correct release to pull. I'll tackle this in the next few days, sorry for the wait :(

Also tysm!

**Comment by srhinos** [comment]
@WybeBosch Okay, I fixed up the way to lean back on my old method of scraping to get the packages. If you dont see an update, delete and reinstall the package on WoWUp!

I'm gonna leave this ticket open because I'd like to reasonably be able to blacklist certain releases by name so I can use the CF API as its faster and safer but this is solved on your end and you shouldn't see any more issues with at least postal!

**Comment by WybeBosch** [comment]
@srhinos Thanks for your fix! Just checked it out and the problem seems to be fixed indeed.

**Comment by srhinos** [comment]
Finally got around to this, fixed the issue with nolib so back to quick releases instead of old scraping methods :D
