### ISSUE TITLE
[REQ] New Addon Request

### ISSUE THREAD

**Issue by Mon3yb** [curseforge-mirror/.github#6]
Addon Name: Arkinventory
Curseforge URL: https://www.curseforge.com/wow/addons/ark-inventory

**Comment by srhinos** [comment]
This addon is All-Rights Reserved as is available thru WoW Interface @ https://www.wowinterface.com/downloads/info6488-ArkInventory.html which doesn't require ads in your addon client.

Due to this, I won't be adding and suggest you use WoWI plus GH mixed unless you can really make a case for not using the WoWI version (like it being constantly outdated).

**Comment by Mon3yb** [comment]
Thank you for checking it. Will use WoWI :)
